name: csbuttons
description: "A Flutter package that provides custom button and animation widgets."
version: 0.1.3
homepage: https://github.com/therasuldev/cs-buttons

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: